RedPacifico/Models/Sales.cs
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.Linq;
using System.Threading.Tasks;

namespace RedPacifico.Models
{
    public class Sales
    {
        public int? SalesId { get; set; }
        public double Downpayment { get; set; }
        public double BonificationDownpayment { get; set; }
        public double Total { get; set; }
        public bool Inactive { get; set; }
    }
}

RedPacifico/ViewModels/SalesViewModels.cs
using Microsoft.AspNetCore.Mvc.Rendering;
using RedPacifico.Models;
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.Linq;
using System.Threading.Tasks;

namespace RedPacifico.ViewModels
{
    public class SalesViewModels
    {
        [Display(Name = "Venta")]
        public int? SalesId { get; set; }

        [Display(Name = "Cliente")]
        [Required(ErrorMessage = "El cliente es requerido")]
        public int CustomerId { get; set; }
        public List<SelectListItem> Customers { get; set; }

        [Display(Name = "Producto")]
        [Required(ErrorMessage = "El producto es requerido")]
        public int ProductId { get; set; }
        public List<SelectListItem> Products { get; set; }

        [Display(Name = "Cantidad")]
        [Required(ErrorMessage = "La cantidad es requerido")]
        [RegularExpression(@"^[0-9]+$",
            ErrorMessage = "Solo se permiten Números")]
        public int? Quantity { get; set; }

        [Display(Name = "Enganche")]
        [RegularExpression(@"^[0-9.]+$",
            ErrorMessage = "Solo se permiten Números")]
        public double Downpayment { get; set; }

        [Display(Name = "Bonificacion Enganche")]
        [RegularExpression(@"^[0-9.]+$",
            ErrorMessage = "Solo se permiten Números")]
        public double BonificationDownpayment { get; set; }

        [Display(Name = "Total")]
        public double Total { get; set; }
        public List<SalesDetails> Details { get; set; }
        public string MessageError { get; set; }
    }
}

RedPacifico/Controllers/SalesController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using RedPacifico.Models;
using RedPacifico.ViewModels;
using RedPacifico.Utilities;

namespace RedPacifico.Controllers
{
    [Authorize]
    public class SalesController : Controller
    {
        private readonly RedPacificoContext _context;
        private MappingService map;

        public SalesController(RedPacificoContext context)
        {
            _context = context;
            map = new MappingService();
        }

        // GET: Sales
        public async Task<IActionResult> Index()
        {
            var settings = await _context.Settings.FirstOrDefaultAsync();
            if (settings == null)
                return RedirectToAction("Edit", "Settings");

            return View(getListSales());
        }

        public IActionResult Edit(int? id)
        {
            var sale = _context.Sales.First(x => x.SalesId == id);
            var vm = map.Map<Sales, SalesViewModels>(sale);
            vm.Details = getSalesDetails(id);
            vm.Customers = getCustomers();
            vm.Products = getProducts();
            calculate(ref vm);
            return View("Create", vm);
        }

        public void calculate(ref SalesViewModels vm)
        {
            var settings = _context.Settings.First(x => !x.Inactive);
            var totalImport = vm.Details.Sum(x => x.Import);
            vm.Downpayment = (settings.Downpayment / 100) * totalImport;
            vm.BonificationDownpayment = (vm.Downpayment * ((settings.FinancingRate * settings.TimeLimit) / 100));
            vm.Total = totalImport - vm.Downpayment - vm.BonificationDownpayment;
        }

        // GET: Sales/Create
        public IActionResult Create()
        {
            SalesViewModels vm = new SalesViewModels();
            vm.Products = getProducts();
            vm.Customers = getCustomers();
            vm.Details = new List<SalesDetails>();
            return View(vm);
        }

        // POST: Sales/Create
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Create([Bind("SalesId,CustomerId,ProductId,Quantity")] SalesViewModels vm)
        {
            if (ModelState.IsValid)
            {
                if (vm.SalesId == null)
                {
                    vm.Downpayment = 0;
                    vm.BonificationDownpayment = 0;
                    vm.Total = 0;
                    var sales = map.Map<SalesViewModels, Sales>(vm);
                    sales.Inactive = true;
                    _context.Add(sales);
                    await _context.SaveChangesAsync();
                    vm.SalesId = sales.SalesId;
                }

                var product = _context.Product.First(x => x.ProductId == vm.ProductId);
                var reserved = _context.SalesDetails.Where(x => x.SalesId == vm.SalesId && !x.Inactive).Sum(x => x.Quantity);
                if (product.Stock < (reserved + vm.Quantity))
                {
                    vm.MessageError = "“El producto seleccionado no cuenta con existencia, favor de verificar”";
                }
                else
                {
                    var settings = _context.Settings.First(x => !x.Inactive);
                    var price = product.Price * (1 + (settings.FinancingRate * settings.TimeLimit) / 100);
                    var import = price * vm.Quantity;
                    var salesDetails = new SalesDetails
                    {
                        CustomerId = vm.CustomerId,
                        ProductId = vm.ProductId,
                        SalesId = vm.SalesId.Value,
                        Inactive = false,
                        Import = import.Value,
                        Price = price,
                        Quantity = vm.Quantity.Value,
                        Available = false
                    };
                    _context.Add(salesDetails);
                    await _context.SaveChangesAsync();
                }
                vm.Details = getSalesDetails(vm.SalesId);
            }
            vm.Customers = getCustomers();
            vm.Products = getProducts();
            calculate(ref vm);
            return View(vm);
        }

        public async Task<IActionResult> Save(int? id)
        {
            var settings = _context.Settings.First(x => !x.Inactive);
            var sale = _context.Sales.First(x => x.SalesId == id);
            var vm = map.Map<Sales, SalesViewModels>(sale);
            vm.Details = getSalesDetails(id);
            calculate(ref vm);
            sale.BonificationDownpayment = vm.BonificationDownpayment;
            sale.Downpayment = vm.Downpayment;
            sale.Total = vm.Total;
            sale.Inactive = false;
            _context.Sales.Update(sale);

            var itemsToUpdate = await _context.SalesDetails.Where(x => x.SalesId == id && !x.Inactive).ToListAsync();
            foreach (var item in itemsToUpdate)
                item.Available = true;

            await _context.SaveChangesAsync();
            return View("Index", getListSales());
        }

        public List<SalesViewModels> getListSales()
        {
            var listSales = _context.Sales.Where(x => !x.Inactive).ToList();
            var customer = new Customer();
            var vm = map.Map<List<Sales>, List<SalesViewModels>>(listSales);
            foreach (var item in vm)
            {
                item.Details = _context.SalesDetails
                        .Include(s => s.Customer)
                        .Include(s => s.Product)
                        .Where(x => x.SalesId == item.SalesId && !x.Inactive && x.Available)
                        .ToList();
            }
            return vm;
        }

        public async Task<IActionResult> Delete(int? id)
        {
            var saleDetail = _context.SalesDetails.First(x => x.SalesDetailsId == id);
            var sale = _context.Sales.First(x => x.SalesId == saleDetail.SalesId);
            saleDetail.Inactive = true;
            _context.SalesDetails.Update(saleDetail);
            await _context.SaveChangesAsync();
            var vm = map.Map<Sales, SalesViewModels>(sale);
            vm.Customers = getCustomers();
            vm.Products = getProducts();
            vm.Details = getSalesDetails(sale.SalesId);
            calculate(ref vm);
            return View("Create", vm);
        }

        private async Task<SalesViewModels> getSales(int? id)
        {
            var sales = await _context.Sales.FindAsync(id);
            var vm = map.Map<Sales, SalesViewModels>(sales);
            vm.Customers = getCustomers();
            vm.Products = getProducts();
            vm.Details = getSalesDetails(sales.SalesId);
            return vm;
        }

        private List<SelectListItem> getCustomers()
        {
            return _context.Customer.OrderBy(u => u.CustomerName)
                .Select(u => new SelectListItem
                {
                    Value = u.CustomerId.ToString(),
                    Text = u.CustomerName
                }).ToList();
        }

        private List<SelectListItem> getProducts()
        {
            return _context.Product.OrderBy(u => u.ProductName)
                .Select(u => new SelectListItem
                {
                    Value = u.ProductId.ToString(),
                    Text = u.ProductName
                }).ToList();
        }

        private List<SalesDetails> getSalesDetails(int? id)
        {
            return _context.SalesDetails
                    .Include(u => u.Product)
                    .Include(u => u.Customer)
                    .Where(u => u.SalesId == id && u.Inactive == false).ToList();
        }
    }
}

RedPacifico/Controllers/SalesDetailsController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using RedPacifico.Models;
using RedPacifico.ViewModels;
using RedPacifico.Utilities;

namespace RedPacifico.Controllers
{
    [Authorize]
    public class SalesDetailsController : Controller
    {
        private readonly RedPacificoContext _context;
        private MappingService map;

        public SalesDetailsController(RedPacificoContext context)
        {
            _context = context;
            map = new MappingService();
        }

        private List<SelectListItem> getCustomers()
        {
            return _context.Customer.OrderBy(u => u.CustomerName)
                .Select(u => new SelectListItem
                {
                    Value = u.CustomerId.ToString(),
                    Text = u.CustomerName
                }).ToList();
        }

        private List<SelectListItem> getProducts()
        {
            return _context.Product.OrderBy(u => u.ProductName)
                .Select(u => new SelectListItem
                {
                    Value = u.ProductId.ToString(),
                    Text = u.ProductName
                }).ToList();
        }

        // GET: SalesDetails/Edit/5
        public async Task<IActionResult> Edit(int? id)
        {
            if (id == null)
                return NotFound();

            var salesDetails = await _context.SalesDetails.FindAsync(id);
            if (salesDetails == null)
                return NotFound();

            var vm = map.Map<SalesDetails, SalesDetailsViewModels>(salesDetails);
            vm.Product = getProducts();
            vm.Customer = getCustomers();
            return View(vm);
        }

        // POST: SalesDetails/Edit/5
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Edit(int? id, [Bind("SalesDetailsId,ProductId,Quantity,Price,Import,SalesId,CustomerId")] SalesDetailsViewModels vm)
        {
            if (id != vm.SalesDetailsId)
                return NotFound();

            var settings = _context.Settings.First(x => !x.Inactive);

            if (ModelState.IsValid)
            {
                try
                {
                    var product = _context.Product.First(x => x.ProductId == vm.ProductId);
                    var reserved = _context.SalesDetails.Where(x => x.SalesId == vm.SalesId && !x.Inactive).Sum(x => x.Quantity);

                    if (product.Stock < (reserved + vm.Quantity))
                    {
                        vm.MessageError = "“El producto seleccionado no cuenta con existencia, favor de verificar”";
                    }
                    else
                    {
                        var price = product.Price * (1 + (settings.FinancingRate * settings.TimeLimit) / 100);
                        vm.Price = price;
                        vm.Import = price * vm.Quantity;
                        var salesDetails = map.Map<SalesDetailsViewModels, SalesDetails>(vm);
                        _context.Update(salesDetails);
                        await _context.SaveChangesAsync();
                    }
                }
                catch (DbUpdateConcurrencyException)
                {
                    if (!SalesDetailsExists(vm.SalesDetailsId))
                        return NotFound();
                    else
                        throw;
                }
            }
            vm.Product = getProducts();
            vm.Customer = getCustomers();
            return View(vm);
        }

        private bool SalesDetailsExists(int? id)
        {
            return _context.SalesDetails.Any(e => e.SalesDetailsId == id);
        }
    }
}

RedPacifico/Views/Sales/Create.cshtml
@model RedPacifico.ViewModels.SalesViewModels;
@{
    ViewData["Title"] = "Registro de Venta";
}
<div class="container">
    <div class="row">
        <div class="col-md-12">
            <label class="h3 text-secondary">@ViewData["Title"]</label>
            <hr />
        </div>
    </div>
    <div class="row">
        <div class="col-xs-12 col-sm-4 col-md-3">
            <form asp-action="Create">
                <div asp-validation-summary="ModelOnly" class="text-danger"></div>
                <input type="text" value="@Model.SalesId" asp-for="@Model.SalesId" hidden />
                <div class="form-group">
                    <label asp-for="CustomerId" class="control-label"></label>
                    <select asp-for="CustomerId" class="form-control" asp-items="Model.Customers">
                        <option value="">----Seleccione un cliente---</option>
                    </select>
                    <span asp-validation-for="CustomerId" class="text-danger"></span>
                </div>
                <div class="form-group">
                    <label asp-for="ProductId" class="control-label"></label>
                    <select asp-for="ProductId" class="form-control" asp-items="Model.Products">
                        <option value="">----Seleccione un producto---</option>
                    </select>
                    <span asp-validation-for="ProductId" class="text-danger"></span>
                </div>
                <div class="form-group">
                    <label asp-for="@Model.Quantity" class="control-label"></label>
                    <input asp-for="@Model.Quantity" class="form-control">
                    <span asp-validation-for="@Model.Quantity" class="text-danger"></span>
                    <p class="text-danger">@Model.MessageError</p>                    
                </div>
                <div class="col-md-12 text-right">
                    <button type="submit" class="btn btn-primary"><i class="fas fa-plus"></i> Agregar</button>
                </div>
            </form>
        </div>
        <div class="col-xs-12 col-sm-8 col-md-9">
            <table class="table table-striped table-hover">
                <thead class="bg-info text-white">
                    <tr>
                        <th scope="col">Descripcion del Producto</th>
                        <th scope="col">Modelo</th>
                        <th scope="col" class="text-center">Cantidad</th>
                        <th scope="col" class="text-center">Precio</th>
                        <th scope="col" class="text-center">Importe</th>
                        <th scope="col"></th>
                    </tr>
                </thead>
                <tbody>
                    @{
                        foreach (var sale in Model.Details)
                        {
                            <tr>
                                <td>@sale.Product.ProductName</td>
                                <td>@sale.Product.Model</td>
                                <td width="10%" class="text-center">@sale.Quantity</td>
                                <td width="10%" class="text-center">@sale.Price</td>
                                <td width="10%" class="text-center">@sale.Import</td>                                
                                <td width="15%" class="text-right">
                                    <a asp-action="Edit" asp-controller="SalesDetails" asp-route-id="@sale.SalesDetailsId" class="btn btn-info btn-sm">
                                        <i class="fas fa-pencil-alt"></i>
                                    </a>
                                    <a asp-action="Delete" asp-route-id="@sale.SalesDetailsId" class="btn btn-danger btn-sm">
                                        <i class="fas fa-trash-alt"></i>
                                    </a>
                                </td>
                            </tr>
                        }
                    }
                </tbody>
            </table>
        </div>
    </div>
    <div class="row">
        <div class="col-xs-12 col-sm-4 col-md-3"></div>
        <div class="col-xs-12 col-sm-8 col-md-9">
            <hr />
            <div class="row">
                <div class="col-xs-6 col-sm-6 col-md-6 text-right"><label asp-for="@Model.Downpayment"></label></div>
                <div class="col-xs-1 col-sm-1 col-md-1">@Model.Downpayment</div>
            </div>
            <div class=" row">
                <div class="col-xs-6 col-sm-6 col-md-6 text-right"><label asp-for="@Model.BonificationDownpayment"></label></div>
                <div class="col-xs-1 col-sm-1 col-md-1">@Model.BonificationDownpayment</div>
            </div>
            <div class=" row">
                <div class="col-xs-6 col-sm-6 col-md-6 text-right"><label asp-for="@Model.Total"></label></div>
                <div class="col-xs-1 col-sm-1 col-md-1">@Model.Total</div>
            </div>
            <div class=" row">
                <div class="col-xs-6 col-sm-6 col-md-6 text-right">
                    <a asp-action="Index" class="btn btn-secondary"><i class="fas fa-undo"></i> Cancelar</a>
                </div>
                <div class="col-xs-6 col-sm-6 col-md-6">
                    <a asp-action="Save" class="btn btn-primary" asp-route-id="@Model.SalesId"><i class="fas fa-save"></i> Guardar</a>
                </div>
            </div>
        </div>
    </div>
</div>


@section Scripts {
    @{await Html.RenderPartialAsync("_ValidationScriptsPartial");}
}

RedPacifico/Views/Sales/Index.cshtml
@model IEnumerable<RedPacifico.ViewModels.SalesViewModels>

@{
    ViewData["Title"] = "Lista de Ventas";
}
<div class="container">
    <div class="row">
        <div class="col-md-12">
            <label class="h3 text-secondary">@ViewData["Title"]</label>
            <hr />
        </div>
    </div>
    <div class="row">
        <div class="col-sm-12 col-md-8 col-lg-7 text-right">
            <a asp-action="Create" class="btn btn-primary"><i class="fas fa-plus"></i> Nueva Venta</a>
        </div>
    </div>
    <div class="row">
        <div class="col-sm-12 col-md-8 col-lg-7">
            <table class="table table-striped table-hover">
                <thead class="bg-info text-white">
                    <tr>
                        <th scope="col">Cliente</th>
                        <th scope="col">Producto</th>
                        <th scope="col">Enganche</th>
                        <th scope="col">Bonificacion enganche</th>
                        <th scope="col">Total</th>
                    </tr>
                </thead>
                <tbody>
                    @{ foreach (var sale in Model) {
                        <tr>
                            <td>
                                @foreach (var detail in sale.Details)
                                {
                                    <a>@detail.Customer.CustomerName </a>
                                    <a>@detail.Customer.LastName </a>
                                    <br />
                                }
                            </td>
                            <td>
                                @foreach (var detail in sale.Details)
                                {
                                    <a>@detail.Product.ProductName </a>
                                    <a>@detail.Product.Model </a>
                                    <br />
                                }
                            </td>
                            <td width="10%" class="text-center">@sale.Downpayment</td>
                            <td width="10%" class="text-center">@sale.BonificationDownpayment</td>
                            <td width="10%" class="text-center">@sale.Total</td>
                        </tr>
                    }}
                </tbody>
            </table>
        </div>
    </div>
</div>